- name: Set fact
  set_fact:
    pattern_str: 'osp_exporter_*'

- name: Set fact
  set_fact:
    pattern_str: 'osp_exporter_{{ podport }}*'
  when: 
    - podport is defined

- name: Find Service files
  find:
    path: /etc/systemd/system
    patterns: "{{ pattern_str }}"
  register: service_filenames 

- name: Stop OSP exporter service
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  vars:
    service_name : "{{ item.path | basename }}"
  with_items:
    - "{{ service_filenames.files }}"
  when: service_filenames.matched > 0

- name: Find the name of the prometheus exporter unarchived directory
  find:
    path: /opt
    patterns: '*osp-exporter*'
    file_type: directory
  register: dir_name

- name: Delete /opt/osp-exporter directory
  file:
    path: "{{ dir_name.files[0].path }}"
    state: absent
  when: 
   - dir_name.matched > 0
   - podport is not defined

- name: Delete /etc/systemd/system/osp_exporter.service
  file:
    path: "{{ service_file_path }}"
    state: absent
  vars:
    service_file_path: "{{ item.path }}"
  with_items:
    - "{{ service_filenames.files }}"
  when: service_filenames.matched > 0

- name: Check if firewalld is installed
  yum:
    list: firewalld
  register: firewalld_op

- name: Close tcp port for OSP exporters
  firewalld:
    port: "{{ portnum }}/tcp"
    permanent: true
    state: disabled
    immediate: true
  vars:
    portnum: "{{ item.path.split('_')[2].split('.')[0] }}"
  with_items:
    - "{{ service_filenames.files }}"
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0 and service_filenames.matched > 0
