- name: Stop prometheus exporter service
  service:
    name: "osp_exporter_{{ portnum }}"
    state: stopped
  with_items: "{{ osp_exporter_config }}"
  vars: 
    portnum: "{{ item.port }}"
- name: Find the name of the prometheus exporter unarchived directory
  find:
    path: /opt
    patterns: '*osp-exporter*'
    file_type: directory
  register: dir_name

- debug: var=dir_name.files[0].path 

- name: Delete /opt/osp-exporter directory
  file:
    path: "{{ dir_name.files[0].path }}"
    state: absent
- name: Delete /etc/systemd/system/osp_exporter.service
  file:
    path: "/etc/systemd/system/osp_exporter_{{ portnum }}.service"
    state: absent
  with_items: "{{ osp_exporter_config }}"
  vars:
    portnum: "{{ item.port }}"

