- name: Find Service files
  find:
    path: /etc/systemd/system
    patterns: 'osp_exporter_*'
  register: service_file 
- debug: var=service_file
- name: Stop prometheus exporter service
  service:
    name: "osp_exporter_{{ portnum }}"
    state: stopped
  with_items: "{{ osp_exporter_config }}"
  vars: 
    portnum: "{{ item.port }}"
  when: service_file.matched > 0
- name: Find the name of the prometheus exporter unarchived directory
  find:
    path: /opt
    patterns: '*osp-exporter*'
    file_type: directory
  register: dir_name

- name: Delete /opt/osp-exporter directory
  file:
    path: "{{ dir_name.files[0].path }}"
    state: absent
  when: dir_name.files[0] is defined

- name: Delete /etc/systemd/system/osp_exporter.service
  file:
    path: "/etc/systemd/system/osp_exporter_{{ portnum }}.service"
    state: absent
  with_items: "{{ osp_exporter_config }}"
  vars:
    portnum: "{{ item.port }}"
- name: Check if firewalld is installed
  yum:
    list: firewalld
  register: firewalld_op

- name: Close tcp port for OSP exporters
  firewalld:
    port: "{{ portnum }}/tcp"
    permanent: true
    state: disabled
    immediate: true
  with_items: "{{ osp_exporter_config }}"
  vars:
    portnum: "{{ item.port }}"
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0
