- name: Find collectd systemd service
  stat:
    path: /usr/lib/systemd/system/collectd.service
  register: service_filename

- name: Stop collectd client
  service:
    name: collectd
    state: stopped
  when: service_filename.stat.path is defined

