collect_plugins:
  - collectd
  - disk

package_dirs:
 src: "{{ telemetry_home }}/roles/client/packages"
 dst: /tmp

collectd_packages_all:
  - collectd-5.8.0-5.el7ost.x86_64.rpm 
  - collectd-disk-5.8.0-5.el7ost.x86_64.rpm




