- name: Download collectd exporter tarball
  unarchive:
    src: "{{ telemetry_home }}/packages/{{ collectd_exporter_pkg }}"
    dest: /opt/

- name: Find the name of the collectd exporter unarchived directory
  find:
    path: /opt
    patterns: '*collectd_exporter*'
    file_type: directory
  register: dir_name

- set_fact: 
    collectd_exporter_path: "{{ dir_name.files[0].path }}"

# The port numbers will be gathered from the group_vars/all file
- name: Set port numbers for collectd exporters
  set_fact:
    collectd_ports: "{{ groups | flatten | select('match', 'pod[0-9]') | map('regex_replace', '_.+$', '') | list | unique | map('regex_replace', '$', '_collectd_port') | map('extract', vars)| list }}"

- name: Create systemd service for collectd exporter
  template:
    src: collectd_exporter_systemd.j2
    dest: "/etc/systemd/system/collectd_exporter_{{ item }}.service"
  with_items: "{{ collectd_ports }}"

#- name: just force systemd to reread configs (2.4 and above)
#  systemd: daemon_reload=yes
#
- name: Start collectd exporter service
  service:
    name: "collectd_exporter_{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items: "{{ collectd_ports }}"

- name: Install latest version firewalld
  yum:
    name: firewalld
    state: latest

- name: Start firewalld service
  service:
    name: firewalld
    state: started

- name: Check if firewalld is installed
  yum:
    list: firewalld
  register: firewalld_op

- name: Open udp port 
  firewalld:
    port: "{{ item }}/udp"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ collectd_ports }}"
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0

- name: Open tcp port 
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  with_items: "{{ collectd_ports }}"
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0
