- name: Copy collectd rpm /tmp
  copy:
    src: "{{ telemetry_home }}/packages/{{ item }}"
    dest: /tmp
  with_items:
    - "{{ collectd_packages_all }}"

- name: Install collectd package
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
    - "{{ collectd_packages_all }}"
    
- name: Extract pod numbers and set collectd_ports
  set_fact:
    collectd_ports: "{{ group_names | flatten | select('match', 'pod[0-9]') | map('regex_replace', '-.+$', '') | list | unique | map('regex_replace', '$', '_port') | map('extract', vars) | list }}"

- name: Configure collectd client to send metrics to collectd exporters
  template:
    src: collectd_conf.j2
    dest: /etc/collectd.conf
  with_items: "{{ collectd_ports }}"

- name: Create /usr/share/collectd/exec directory
  file:
    path: /usr/share/collectd/exec
    state: directory
    mode: 0755

- name: Copy nfvi-services.sh to /etc/collectd.d directory
  copy:
    src: compute-nfvi-services.sh
    dest: /usr/share/collectd/exec/nfvi-services.sh
    mode: 0755
  when: "'computes' in group_names | join(' ')"

- name: Copy nfvi-services.sh to /etc/collectd.d directory
  copy:
    src: controller-nfvi-services.sh
    dest: /usr/share/collectd/exec/nfvi-services.sh
    mode: 0755
  when: "'controllers' in group_names | join(' ')"

- name: Copy types.db.custom to /usr/share/collectd directory
  copy:
    src: types.db.custom
    dest: /usr/share/collectd/

- name: Set selinux permissive for collectd
  selinux_permissive:
    name: collectd_t
    permissive: true

- name: Create sudoers file for nobody
  copy:
    src: nobody.sudoers
    dest: /etc/sudoers.d/nobody

- name: Start collectd client
  service:
    name: collectd
    state: restarted
    enabled: yes
