- name: Copy collectd rpm /tmp
  copy:
    src: "{{ telemetry_home }}/packages/{{ item }}"
    dest: /tmp
  with_items:
    - "{{ collectd_packages_all }}"

- name: Install collectd package
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
    - "{{ collectd_packages_all }}"
    
- name: Configure collectd client to send metrics to collectd exporter
  template:
    src: collectd_conf.j2
    dest: /etc/collectd.conf

- name: Copy nfvi-services.sh to /etc/collectd.d directory
  copy:
    src: nfvi-services.sh
    dest: /etc/collectd.d/nfvi-services.sh
    mode: 0755

- name: Start collectd client
  service:
    name: collectd
    state: restarted
