- name: Copy collectd rpm /tmp
  copy:
    src: "{{ package_dirs.src }}/{{ item }}"
    dest: "{{ package_dirs.dst }}/{{ item }}"
  with_items:
    - "{{ collectd_packages_all }}"

- name: Install collectd package
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
    - "{{ collectd_packages_all }}"
    
- name: Configure collectd client to send metrics to collectd exporter
  template:
    src: collectd_conf.j2
    dest: /etc/collectd.conf

- name: Copy mavenir-nfvi.sh to /etc/collectd.d directory
  copy:
    src: mavenir-nfvi.sh
    dest: /etc/collectd.d/mavenir-nfvi.sh
    mode: 0755

- name: Start collectd client
  service:
    name: collectd
    state: restarted
