- name: Copy collectd rpm /tmp
  copy:
    src: "{{ telemetry_home }}/packages/{{ item }}"
    dest: /tmp
  with_items:
    - "{{ collectd_packages_all }}"

- name: Install collectd package
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
    - "{{ collectd_packages_all }}"
    
- name: Configure collectd client to send metrics to collectd exporter
  template:
    src: collectd_conf.j2
    dest: /etc/collectd.conf

- name: Copy nfvi-services.sh to /etc/collectd.d directory
  copy:
    src: compute-nfvi-services.sh
    dest: /etc/collectd.d/nfvi-services.sh
    mode: 0755
  when: "'osp-computes' in group_names"

- name: Copy nfvi-services.sh to /etc/collectd.d directory
  copy:
    src: controller-nfvi-services.sh
    dest: /etc/collectd.d/nfvi-services.sh
    mode: 0755
  when: "'osp-controllers' in group_names"

- name: Copy discover-disks.sh to /usr/local/sbin directory
  copy:
    src: discover_disk.sh
    dest: /usr/local/sbin/
    mode: 0755

- name: Copy netif_discovery.sh to /usr/local/sbin directory
  copy:
    src: netif_discovery.sh
    dest: /usr/local/sbin/
    mode: 0755

- name: Ensure netif_discovery.sh.log file is owned by nobody
  file: 
    path: /var/log/netif_discovery.sh.log
    owner: nobody
    group: nobody
    state: touch

- name: Copy smart-health.sh to /usr/local/sbin directory
  copy:
    src: smart-health.sh
    dest: /usr/local/sbin/
    mode: 0755

- name: Copy smart-temp.sh to /usr/local/sbin directory
  copy:
    src: smart-temp.sh
    dest: /usr/local/sbin/
    mode: 0755

- name: Copy types.db.custom to /usr/share/collectd directory
  copy:
    src: types.db.custom
    dest: /usr/share/collectd/

- name: Start collectd client
  service:
    name: collectd
    state: restarted
