- name: Copy collectd rpm /tmp
  copy:
    src: "{{ telemetry_home }}/packages/{{ item }}"
    dest: /tmp
  with_items:
    - "{{ collectd_packages_all }}"

- name: Install collectd package
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
    - "{{ collectd_packages_all }}"
    
- name: Configure collectd client to send metrics to collectd exporters
  template:
    src: collectd_conf.j2
    dest: /etc/collectd.conf
  vars:
    portnum: "{{ item.port }}"
  with_items: "{{ collectd_exporter_config }}"
  when: item.name|lower in group_names|lower

- name: Create /usr/share/collectd/exec directory
  file:
    path: /usr/share/collectd/exec
    state: directory
    mode: 0755

- name: Create nfvi-services.sh for compute nodes
  template:
    src: compute-nfvi-services-sh.j2
    dest: /usr/share/collectd/exec/nfvi-services.sh
    mode: 0755
  when: "'computes' in group_names | join(' ')"

- name: Create nfvi-services.sh for controllers from template
  template:
    src: controller-nfvi-services-sh.j2
    dest: /usr/share/collectd/exec/nfvi-services.sh
    mode: 0755
  when: "'controllers' in group_names | join(' ')"

- name: Copy types.db.custom to /usr/share/collectd directory
  copy:
    src: types.db.custom
    dest: /usr/share/collectd/

- name: Set selinux permissive for collectd
  selinux_permissive:
    name: collectd_t
    permissive: true

- name: Create sudoers file for nobody
  copy:
    src: nobody.sudoers
    dest: /etc/sudoers.d/nobody

- name: Start collectd client
  service:
    name: collectd
    state: restarted
    enabled: yes
