- name: Copy collectd and ceph plugin rpm to /tmp
  copy:
    src: "{{ telemetry_home }}/packages/{{ item }}"
    dest: /tmp
  with_items:
    - "{{ collectd_packages_all }}"
    - "{{ collectd_packages_ceph }}"

- name: Install collectd and ceph plugin packages
  yum:
    name: "/tmp/{{ item }}"
    state: present
  with_items:
    - "{{ collectd_packages_all }}"
    - "{{ collectd_packages_ceph }}"

- name: Extract pod numbers and set collectd_ports
  set_fact:
    collectd_ports: "{{ group_names | flatten | select('match', 'pod[0-9]') | map('regex_replace', '_.+$', '') | list | unique | map('regex_replace', '$', '_collectd_port') | map('extract', vars) | list }}"

- name: Configure collectd client to send metrics to collectd exporter
  template:
    src: collectd_conf.j2
    dest: /etc/collectd.conf
  with_items: "{{ collectd_ports }}"

- name: Create /usr/share/collectd/exec directory
  file:
    path: /usr/share/collectd/exec
    state: directory
    mode: 0755

- name: Copy nfvi-services.sh to /usr/share/collectd/exec directory
  copy:
    src: ceph-osd-nfvi-services.sh
    dest: /usr/share/collectd/exec/nfvi-services.sh
    mode: 0755
  when: "'osd' in group_names | join(' ')"

- name: Copy nfvi-services.sh to /usr/share/collectd/exec directory
  copy:
    src: ceph-mon-nfvi-services.sh
    dest: /usr/share/collectd/exec/nfvi-services.sh
    mode: 0755
  when: "'mon' in group_names | join(' ')"

- name: Copy ceph-status.sh to /usr/local/sbin directory
  copy:
    src: ceph-status.sh
    dest: /usr/local/sbin/
    force: no
    mode: 0755

- name: Copy types.db.custom to /usr/share/collectd directory
  copy:
    src: types.db.custom
    dest: /usr/share/collectd/

- name: Find all *asok files of OSDs
  find:
    path: /var/run/ceph/
    pattern: "*.asok"
    file_type: any
  register: daemons

- name: Copy 90-ceph-plugin configuration
  template:
    src: 90-ceph-plugin-conf.j2
    dest: /etc/collectd.d/90-ceph-plugin.conf

- name: Create sudoers file for nobody
  copy:
    src: nobody.sudoers
    dest: /etc/sudoers.d/nobody

- name: Start collectd client
  service:
    name: collectd
    state: restarted
    enabled: yes
