- name: Find collectd systemd service
  stat:
    path: /usr/lib/systemd/system/collectd.service
  register: service_filename

- name: Stop collectd client
  service:
    name: collectd
    state: stopped
    enabled: no
  when: service_filename.stat.path is defined

- name: Uninstall collectd packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ collectd_plugins }}"
    
- name: Remove sudoers file for nobody
  file:
    path: /etc/sudoers.d/nobody
    state: absent

- name: Unset selinux permissive for collectd
  selinux_permissive:
    name: collectd_t
    permissive: false

- name: Delete /usr/share/collectd directory and it's contents
  file:
    path: /usr/share/collectd
    state: absent

- name: Delete /etc/collectd.d directory and it's contents
  file:
    path: /etc/collectd.d
    state: absent

- name: Delete /etc/collectd.conf file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/collect.conf
    - /etc/collectd.conf.rpmsave

- name: Remove collectd package files from /tmp
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "{{ collectd_packages_all }}"
    - "{{ collectd_packages_ceph }}"
    - collectd.conf

- name: Remove collectd log file
  file:
    path: /var/log/collectd.log
    state: absent

- name: If ceph mon or osd node, remove ceph-status.sh from /usr/local/sbin directory
  file:
    dest: /usr/local/sbin/ceph-status.sh
    state: absent
  when: ("'osd' in group_names | join(' ')") or ("'mon' in group_names | join(' ')")
