
- name: Copy packages required for osp-exporter /tmp
  copy:
    src: "{{ telemetry_home }}/packages/{{ prometheus_client }}"
    dest: /tmp

- name: Install Python Prometheus Client
  pip:
    name: "/tmp/{{ prometheus_client }}"

- name: Copy OSP exporter python files to target 
  copy:
    src: osp-exporter
    dest: /opt

- name: Find the name of the prometheus exporter directory
  find:
    path: /opt
    patterns: '*osp-exporter*'
    file_type: directory
  register: dir_name

- debug: var=dir_name.files[0].path

- set_fact:
    osp_exporter_path: "{{ dir_name.files[0].path }}"

- name: Set main.py to be executable
  file:
    path: "{{ osp_exporter_path }}/main.py"
    mode: 0755

- name: Create config file env.yaml
  template:
    src: env.yaml.j2
    dest: "{{ osp_exporter_path }}/env_{{ item.port }}.yaml"
  with_items: "{{ osp_exporter_config }}"

- name: Create systemd service for prometheus exporter
  template:
    src: osp_exporter_systemd.j2
    dest: "/etc/systemd/system/osp_exporter_{{ item.port }}.service"
  with_items: "{{ osp_exporter_config }}"

- name: Start prometheus exporter service
  systemd:
    name: "osp_exporter_{{ item.port }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items: "{{ osp_exporter_config }}"
