# The port numbers will be gathered from the group_vars/all file
- name: Find collectd systemd service
  find:
    path: /etc/systemd/system
    pattern: 'collectd_exporter_*'
  register: service_filenames

- name: Stop collectd exporter services
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  vars:
    service_name : "{{ item.path | basename }}"
  with_items: 
    - "{{ service_filenames.files }}"
  when: service_filenames.files[0] is defined

- name: Find the name of the collectd exporter unarchived directory
  find:
    path: /opt
    patterns: '*collectd_exporter*'
    file_type: directory
  register: dir_name

- name: Delete /opt/collectd-exporter directory
  file:
    path: "{{ dir_name.files[0].path }}"
    state: absent
  when: dir_name.files[0] is defined
  

- name: Delete collectd systemd service files
  file:
    path: "{{ service_file_path }}"
    state: absent
  vars:
    service_file_path: "{{ item.path }}"
  with_items: 
    - "{{ service_filenames.files }}"
  when: service_filenames.files[0] is defined

- name: Check if firewalld is installed
  yum:
    list: firewalld
  register: firewalld_op

- name: Close tcp ports for collectd exporter
  firewalld:
    port: "{{ portnum }}/tcp"
    permanent: true
    state: disabled
    immediate: true
  vars:
    portnum: "{{ item.path.split('_')[2].split('.')[0] }}"
  with_items: 
    - "{{ service_filenames.files }}"
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0 and service_filenames.files[0] is defined

- name: Close udp ports for collectd exporter
  firewalld:
    port: "{{ portnum }}/udp"
    permanent: true
    state: disabled
    immediate: true
  vars:
    portnum: "{{ item.path.split('_')[2].split('.')[0] }}"
  with_items: 
    - "{{ service_filenames.files }}"
  when: firewalld_op.results|selectattr("yumstate", "match", "installed")|list|length != 0 and service_filenames.files[0] is defined
