- name: Find snmptrapper systemd service
  find:
    path: /etc/systemd/system
    pattern: '*snmptrapper*'
    file_type: file
  register: service_filename

- debug: var=service_filename.files[0].path
  when: service_filename.files[0] is defined

- name: Stop snmptrapper service
  service:
    name: snmptrapper
    state: stopped
  when: service_filename.files[0] is defined

- name: Find the name of the snmptrapper unarchived directory
  find:
    path: /opt
    pattern: '*snmptrapper*'
    file_type: directory
  register: dir_name

- debug: var=dir_name.files[0].path
  when: dir_name.files[0] is defined

- name: Delete /opt/snmptrapper directory
  file:
    path: "{{ dir_name.files[0].path }}"
    state: absent
  when: dir_name.files[0] is defined

- name: Delete /etc/systemd/system/snmptrapper.service
  file:
    path: "{{ service_filename.files[0].path }}"
    state: absent
  when: service_filename.files[0] is defined
